export const LOAD_USER_TOKEN = 'LOAD_USER_TOKEN';
export const LOAD_USER_TOKEN_PAYLOAD = 'LOAD_USER_TOKEN_PAYLOAD';
export const DELETE_STORE = 'DELETE_STORE';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_CART = 'GET_CART';
